#ifndef PERSON_CONTROLLER_FACTORY_H
#define PERSON_CONTROLLER_FACTORY_H

#include "person_controller_base.h"

typedef enum PERSON_CONTROLLER_TYPE_T
{
    PERSON_CONTROLLER_TYPE_CLI,
    PERSON_CONTROLLER_TYPE_GTK,
    PERSON_CONTROLLER_TYPE_WEBSERVER,
} PERSON_CONTROLLER_TYPE_T;

PERSON_CONTROLLER_BASE_T person_controller_factory_create(const char *type, PERSON_CONTROLLER_ARGS_T *args);

#endif /* PERSON_CONTROLLER_FACTORY_H */